const translations = {
    ar: {
        appName: 'مساري',
        expenses: 'المصاريف',
        salaries: 'الرواتب',
        revenue: 'الإيرادات',
        freelance: 'الفريلانس',
        whatsapp: 'اشتراكات الواتساب',
        goals: 'الأهداف المالية',
        certificates: 'الشهادات البنكية',
        reports: 'التقارير',
        optimization: 'الترشيد',
        settings: 'الإعدادات',
        addExpense: 'إضافة مصروف',
        addSalary: 'إضافة راتب',
        addRevenue: 'إضافة إيراد',
        addGoal: 'إضافة هدف',
        addCertificate: 'إضافة شهادة',
        monthlySalary: 'الراتب الشهري',
        company: 'الشركة',
        amount: 'المبلغ',
        date: 'التاريخ',
        category: 'التصنيف',
        notes: 'ملاحظات',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        total: 'الإجمالي',
        remaining: 'المتبقي',
        paid: 'مدفوع',
        dashboard: 'لوحة التحكم',
        notifications: 'التنبيهات',
        backup: 'نسخ احتياطي',
        restore: 'استعادة',
        currency: 'EGP',
        balance: 'الرصيد',
        view: 'عرض',
        upcomingReminders: 'تذكيرات قادمة',
        remindersPending: 'تذكيرات معلقة',
        name: 'الاسم',
        confirmDelete: 'هل أنت متأكد من الحذف؟',
        recurring: 'متكرر',
        food: 'طعام',
        transport: 'مواصلات',
        bills: 'فواتير',
        shopping: 'تسوق',
        health: 'صحة',
        education: 'تعليم',
        entertainment: 'ترفيه',
        other: 'أخرى',
        selectCategory: 'اختر التصنيف',
        expenseReminder: 'تذكير مصروف',
        clientName: 'اسم العميل',
        projectName: 'اسم المشروع',
        duration: 'المدة',
        durationPlaceholder: 'مثال: 3 أشهر',
        totalAmount: 'المبلغ الإجمالي',
        dueDate: 'تاريخ الاستحقاق',
        addPayment: 'إضافة دفعة',
        invoice: 'فاتورة',
        payments: 'الدفعات',
        type: 'النوع',
        payment: 'دفعة',
        settlement: 'تسديد',
        discount: 'خصم',
        refund: 'إرجاع',
        system: 'النظام',
        systemType: 'نوع النظام',
        system1: 'النظام الأول',
        system2: 'النظام الثاني',
        plan: 'الباقة',
        refresh: 'تحديث',
        addCustomer: 'إضافة عميل',
        renew: 'تجديد',
        upgrade: 'ترقية',
        stop: 'إيقاف',
        status: 'الحالة',
        active: 'نشط',
        stopped: 'متوقف',
        expired: 'منتهي',
        startDate: 'تاريخ البداية',
        endDate: 'تاريخ النهاية',
        subscriptionId: 'رقم الاشتراك',
        title: 'العنوان',
        targetAmount: 'المبلغ المستهدف',
        currentAmount: 'المبلغ الحالي',
        deadline: 'الموعد النهائي',
        enableReminders: 'تفعيل التذكيرات',
        addAmount: 'إضافة مبلغ',
        noGoals: 'لا توجد أهداف مالية بعد',
        bankName: 'اسم البنك',
        certificateNumber: 'رقم الشهادة',
        depositDate: 'تاريخ الإيداع',
        maturityDate: 'تاريخ الاستحقاق',
        totalWithdrawn: 'إجمالي المسحوب',
        totalRepaid: 'إجمالي المدفوع',
        pendingRepayment: 'المتبقي للسداد',
        withdrawals: 'السحوبات',
        addWithdrawal: 'إضافة سحب',
        repaymentNotice: 'يجب سداد السحب قبل 55 يوم من تاريخه',
        markRepaid: 'تسديد',
        repaid: 'مدفوع',
        withdrawalDeadline: 'موعد استرداد السحب',
        certificate: 'شهادة',
        certificateName: 'اسم الشهادة',
        certificateNamePlaceholder: 'مثال: شهادة ادخار 3 سنوات',
        certificateValue: 'قيمة الشهادة',
        monthlyReturn: 'العائد الشهري',
        monthlyReturnPlaceholder: 'الربح الشهري من الشهادة',
        remainingAmount: 'المتبقي',
        dangerousWithdrawals: 'سحوبات خطرة تحتاج للسداد العاجل!',
        dangerousWithdrawalsDesc: 'لديك سحوبات قاربت على 55 يوم وتحتاج للسداد فوراً',
        dangerous: 'خطرة',
        scheduleAsInstallments: 'جدولة كأقساط',
        installmentsExempt55Days: 'الأقساط معفاة من شرط ال 55 يوم',
        installmentCount: 'عدد الأقساط',
        installments: 'أقساط',
        installmentPlan: 'جدول أقساط',
        payInstallment: 'دفع قسط',
        availableAmount: 'المبلغ المتاح',
        insufficientCertificateFunds: 'المبلغ المتاح غير كافي',
        amountReturned: 'المبلغ عاد للمتاح',
        daysLeft: 'أيام متبقية',
        certificateReturn: 'عائد شهادة',
        certificateReturnAdded: 'تم إضافة العائد الشهري تلقائياً',
        returnDayOfMonth: 'يوم نزول العائد',
        dayOfMonthPlaceholder: 'مثال: 5',
        returnDayOfMonthHelp: 'سيتم إضافة العائد تلقائياً في نفس اليوم من كل شهر',
        day: 'يوم',
        ofEachMonth: 'من كل شهر',
        lastReturnDate: 'آخر عائد',
        savingsFund: 'الصندوق الادخاري',
        maxWithdrawalLimit: 'الحد الأقصى للسحب',
        maxWithdrawalLimitPlaceholder: 'اتركه فارغاً إذا كان يساوي قيمة الشهادة',
        maxWithdrawalLimitHelp: 'الحد الائتماني المسموح به من البنك للسحب (اختياري - إذا كان أقل من قيمة الشهادة)',
        maxWithdrawalLimitExceedsAmount: 'الحد الأقصى للسحب لا يمكن أن يتجاوز قيمة الشهادة',
        gold: 'الأوعية الذهبية',
        addGoldPurchase: 'إضافة شراء ذهب',
        goldPurchases: 'المشتريات',
        goldPurchasesList: 'قائمة المشتريات',
        noGoldPurchases: 'لا توجد مشتريات ذهب',
        invoiceValue: 'قيمة الفاتورة',
        grams: 'الجرامات',
        gram: 'جرام',
        pricePerGram: 'سعر الجرام',
        purity: 'العيار',
        carat: 'قيراط',
        goldType: 'نوع الذهب',
        goldBar: 'سبيكة',
        goldCoin: 'جنيه ذهب',
        halfGoldCoin: 'نصف جنيه ذهب',
        quarterGoldCoin: 'ربع جنيه ذهب',
        goldRing: 'خاتم',
        goldEarring: 'حلق',
        goldNecklace: 'انسيال / قلادة',
        goldBracelet: 'سوار',
        goldChain: 'سلسلة',
        goldPendant: 'قلادة',
        goldBrooch: 'بروش',
        otherGold: 'أخرى',
        purchaseDate: 'تاريخ الشراء',
        remaining: 'المتبقي',
        sold: 'مباع',
        sellGold: 'بيع ذهب',
        sell: 'بيع',
        saleValue: 'قيمة البيع الإجمالية',
        saleDate: 'تاريخ البيع',
        salesHistory: 'سجل المبيعات',
        profitLoss: 'الربح/الخسارة',
        purchaseInfo: 'معلومات الشراء',
        totalGoldPurchases: 'إجمالي المشتريات',
        totalGoldSales: 'إجمالي المبيعات',
        totalProfitLoss: 'إجمالي الربح/الخسارة',
        insufficientGold: 'لا يوجد ذهب كافي',
        pleaseEnterValidValues: 'يرجى إدخال قيم صحيحة',
        thisMonth: 'هذا الشهر',
        lastMonth: 'الشهر الماضي',
        thisYear: 'هذا العام',
        totalIncome: 'إجمالي الدخل',
        totalExpenses: 'إجمالي المصاريف',
        expensesByCategory: 'المصاريف حسب التصنيف',
        monthlyComparison: 'المقارنة الشهرية',
        optimization: 'الترشيد',
        recommendations: 'التوصيات',
        savingsOpportunities: 'فرص التوفير',
        tooManyRecurring: 'مصاريف متكررة كثيرة',
        recurringRecommendation: 'راجع المصاريف المتكررة وألغِ ما لا تحتاجه',
        highSpending: 'إنفاق عالي',
        highSpendingMessage: 'إنفاقك على',
        isHigh: 'عالي. يمكنك الترشيد فيه',
        savingsGoal: 'هدف التوفير',
        savingsGoalMessage: 'حاول توفير 20% من دخلك الشهري',
        noData: 'لا توجد بيانات كافية للتحليل',
        tips: 'نصائح',
        foodTip1: 'طبخ وجبات كافية للأسبوع',
        foodTip2: 'استخدم قائمة تسوق و التزم بها',
        foodTip3: 'تجنب الأكل خارج البيت بكثرة',
        transportTip1: 'استخدم المواصلات العامة',
        transportTip2: 'شارك في الرحلات مع الآخرين',
        transportTip3: 'استخدم الدراجة للمسافات القصيرة',
        billsTip1: 'أطفئ الأجهزة غير المستخدمة',
        billsTip2: 'استخدم لمبات LED موفرة للطاقة',
        billsTip3: 'راقب استهلاك الماء والكهرباء',
        shoppingTip1: 'قارن الأسعار قبل الشراء',
        shoppingTip2: 'استخدم كوبونات الخصم',
        shoppingTip3: 'تجنب التسوق العاطفي',
        generalTip1: 'راقب مصاريفك بانتظام',
        generalTip2: 'ضع ميزانية شهرية',
        generalTip3: 'وفر 20% من دخلك كل شهر',
        currentSpending: 'الإنفاق الحالي',
        potentialSaving: 'التوفير المحتمل',
        language: 'اللغة',
        general: 'عام',
        soundNotifications: 'التنبيهات الصوتية',
        soundNotificationsDesc: 'تفعيل الأصوات للتنبيهات',
        emailNotifications: 'التنبيهات بالإيميل',
        emailNotificationsDesc: 'إرسال تنبيهات عبر البريد الإلكتروني',
        email: 'البريد الإلكتروني',
        enterEmail: 'أدخل البريد الإلكتروني',
        exportBackup: 'تصدير النسخة الاحتياطية',
        exportBackupDesc: 'حفظ جميع بياناتك كملف JSON',
        export: 'تصدير',
        importBackup: 'استيراد النسخة الاحتياطية',
        importBackupDesc: 'استعادة البيانات من ملف النسخة الاحتياطية',
        import: 'استيراد',
        appearance: 'المظهر',
        theme: 'المظهر',
        light: 'فاتح',
        dark: 'داكن',
        auto: 'تلقائي',
        backupExported: 'تم تصدير النسخة الاحتياطية بنجاح',
        backupImported: 'تم استيراد النسخة الاحتياطية بنجاح',
        backupError: 'حدث خطأ',
        monthlyRecurring: 'راتب شهري تلقائي',
        dayOfMonth: 'يوم الشهر',
        dayOfMonthPlaceholder: 'مثال: 5',
        dayOfMonthHelp: 'سيتم إضافة الراتب تلقائياً في نفس اليوم من كل شهر',
        ofEachMonth: 'من كل شهر',
        recurringSalaries: 'الرواتب الشهرية التلقائية',
        regularSalaries: 'الرواتب العادية',
        lastAdded: 'آخر إضافة',
        checkNow: 'تحقق الآن',
        autoAdded: 'مضاف تلقائياً',
        salaryAdded: 'تم إضافة الراتب تلقائياً',
        monthlyExpense: 'مصروف شهري',
        autoAddMonthly: 'إضافة تلقائية كل شهر',
        expenseDayOfMonthHelp: 'سيتم إضافة المصروف تلقائياً في نفس اليوم من كل شهر',
        recurringMonthlyExpenses: 'المصاريف الشهرية التلقائية',
        regularExpenses: 'المصاريف العادية',
        manageCategories: 'إدارة البنود',
        categoryName: 'اسم التصنيف',
        enterCategoryName: 'أدخل اسم التصنيف',
        icon: 'الأيقونة',
        color: 'اللون',
        addCategory: 'إضافة تصنيف',
        existingCategories: 'التصنيفات الموجودة',
        cannotDeleteDefault: 'لا يمكن حذف التصنيف الافتراضي',
        errorAddingCategory: 'خطأ في إضافة التصنيف',
        errorDeletingCategory: 'خطأ في حذف التصنيف',
        expenseAdded: 'تم إضافة المصروف تلقائياً',
        totalSalaries: 'إجمالي الرواتب',
        pleaseEnterCategoryName: 'يرجى إدخال اسم التصنيف',
        categoryAlreadyExists: 'التصنيف موجود بالفعل',
        databaseError: 'خطأ في قاعدة البيانات. يرجى تحديث الصفحة',
        categoryAddedSuccessfully: 'تم إضافة التصنيف بنجاح',
        noCategories: 'لا توجد تصنيفات',
        confirmDeleteCategory: 'هل أنت متأكد من حذف هذا التصنيف؟',
        categoryDeletedSuccessfully: 'تم حذف التصنيف بنجاح',
        deleteAllData: 'حذف جميع البيانات',
        deleteAllDataDesc: 'سيتم إنشاء نسخة احتياطية تلقائياً قبل الحذف، ثم حذف جميع البيانات بشكل نهائي',
        deleteAll: 'حذف الكل',
        dangerZone: 'المنطقة الخطيرة',
        confirmDeleteAllData: '⚠️ تحذير: سيتم حذف جميع البيانات!\n\nسيتم إنشاء نسخة احتياطية تلقائياً قبل الحذف.\nهل أنت متأكد تماماً؟\n\nاكتب "حذف" للتأكيد:',
        finalConfirmDelete: '⚠️ تأكيد نهائي!\n\nسيتم حذف جميع بياناتك بشكل نهائي.\nالنسخة الاحتياطية تم إنشاءها بالفعل.\n\nهل أنت متأكد 100%؟',
        allDataDeleted: 'تم حذف جميع البيانات بنجاح. تم إنشاء نسخة احتياطية تلقائياً.',
        allDataDeletedSuccess: '✅ تم حذف جميع البيانات بنجاح!\n\nتم إنشاء نسخة احتياطية تلقائياً قبل الحذف.\nسيتم إعادة تحميل الصفحة الآن.',
        deleteError: 'حدث خطأ أثناء حذف البيانات',
        deleteCancelled: 'تم إلغاء العملية. لم يتم حذف أي بيانات.',
        backupFailedBeforeDelete: 'فشل إنشاء النسخة الاحتياطية قبل الحذف',
        errorCheckingExpenses: 'خطأ في فحص المصاريف التلقائية',
        // Activity Log
        activityLog: 'سجل العمليات',
        filters: 'تصفية',
        entityType: 'نوع العملية',
        action: 'الإجراء',
        clearFilters: 'مسح التصفية',
        clearOldActivities: 'حذف السجلات القديمة',
        clearAllActivities: 'حذف جميع السجلات',
        confirmClearOldActivities: 'هل تريد حذف السجلات القديمة (أكثر من سنة)؟',
        oldActivitiesCleared: 'تم حذف السجلات القديمة بنجاح',
        confirmClearAllActivities: 'هل أنت متأكد من حذف جميع السجلات؟',
        allActivitiesCleared: 'تم حذف جميع السجلات',
        noActivities: 'لا توجد عمليات مسجلة',
        added: 'إضافة',
        updated: 'تعديل',
        deleted: 'حذف',
        sold: 'بيع',
        purchased: 'شراء',
        repaid: 'سداد',
        withdrawn: 'سحب',
        paid: 'دفع',
        // Entity labels
        expense: 'مصروف',
        salary: 'راتب',
        certificate: 'شهادة',
        certificateWithdrawal: 'سحب',
        goldPurchase: 'شراء ذهب',
        goldSale: 'بيع ذهب',
        goal: 'هدف',
        category: 'فئة'
    },
    en: {
        appName: 'Msarefy',
        expenses: 'Expenses',
        salaries: 'Salaries',
        revenue: 'Revenue',
        freelance: 'Freelance',
        whatsapp: 'WhatsApp Subscriptions',
        goals: 'Financial Goals',
        certificates: 'Bank Certificates',
        reports: 'Reports',
        optimization: 'Optimization',
        settings: 'Settings',
        addExpense: 'Add Expense',
        addSalary: 'Add Salary',
        addRevenue: 'Add Revenue',
        addGoal: 'Add Goal',
        addCertificate: 'Add Certificate',
        monthlySalary: 'Monthly Salary',
        company: 'Company',
        amount: 'Amount',
        date: 'Date',
        category: 'Category',
        notes: 'Notes',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        total: 'Total',
        remaining: 'Remaining',
        paid: 'Paid',
        dashboard: 'Dashboard',
        notifications: 'Notifications',
        backup: 'Backup',
        restore: 'Restore',
        currency: 'EGP',
        balance: 'Balance',
        view: 'View',
        upcomingReminders: 'Upcoming Reminders',
        remindersPending: 'Pending Reminders',
        name: 'Name',
        confirmDelete: 'Are you sure you want to delete?',
        recurring: 'Recurring',
        food: 'Food',
        transport: 'Transport',
        bills: 'Bills',
        shopping: 'Shopping',
        health: 'Health',
        education: 'Education',
        entertainment: 'Entertainment',
        other: 'Other',
        selectCategory: 'Select Category',
        expenseReminder: 'Expense Reminder',
        clientName: 'Client Name',
        projectName: 'Project Name',
        duration: 'Duration',
        durationPlaceholder: 'e.g., 3 months',
        totalAmount: 'Total Amount',
        dueDate: 'Due Date',
        addPayment: 'Add Payment',
        invoice: 'Invoice',
        payments: 'Payments',
        type: 'Type',
        payment: 'Payment',
        settlement: 'Settlement',
        discount: 'Discount',
        refund: 'Refund',
        system: 'System',
        systemType: 'System Type',
        system1: 'System 1',
        system2: 'System 2',
        plan: 'Plan',
        refresh: 'Refresh',
        addCustomer: 'Add Customer',
        renew: 'Renew',
        upgrade: 'Upgrade',
        stop: 'Stop',
        status: 'Status',
        active: 'Active',
        stopped: 'Stopped',
        expired: 'Expired',
        startDate: 'Start Date',
        endDate: 'End Date',
        subscriptionId: 'Subscription ID',
        title: 'Title',
        targetAmount: 'Target Amount',
        currentAmount: 'Current Amount',
        deadline: 'Deadline',
        enableReminders: 'Enable Reminders',
        addAmount: 'Add Amount',
        noGoals: 'No financial goals yet',
        bankName: 'Bank Name',
        certificateNumber: 'Certificate Number',
        depositDate: 'Deposit Date',
        maturityDate: 'Maturity Date',
        totalWithdrawn: 'Total Withdrawn',
        totalRepaid: 'Total Repaid',
        pendingRepayment: 'Pending Repayment',
        withdrawals: 'Withdrawals',
        addWithdrawal: 'Add Withdrawal',
        repaymentNotice: 'Withdrawal must be repaid within 55 days',
        markRepaid: 'Mark as Repaid',
        repaid: 'Repaid',
        withdrawalDeadline: 'Withdrawal Deadline',
        certificate: 'Certificate',
        certificateName: 'Certificate Name',
        certificateNamePlaceholder: 'e.g., 3-Year Savings Certificate',
        certificateValue: 'Certificate Value',
        monthlyReturn: 'Monthly Return',
        monthlyReturnPlaceholder: 'Monthly profit from certificate',
        remainingAmount: 'Remaining',
        dangerousWithdrawals: 'Dangerous Withdrawals Need Urgent Payment!',
        dangerousWithdrawalsDesc: 'You have withdrawals approaching 55 days that need immediate payment',
        dangerous: 'Dangerous',
        scheduleAsInstallments: 'Schedule as Installments',
        installmentsExempt55Days: 'Installments are exempt from the 55-day requirement',
        installmentCount: 'Number of Installments',
        installments: 'Installments',
        installmentPlan: 'Installment Plan',
        payInstallment: 'Pay Installment',
        availableAmount: 'Available Amount',
        insufficientCertificateFunds: 'Insufficient funds in certificate',
        amountReturned: 'Amount returned to available balance',
        daysLeft: 'Days Left',
        certificateReturn: 'Certificate Return',
        certificateReturnAdded: 'Certificate return added automatically',
        returnDayOfMonth: 'Return Day of Month',
        dayOfMonthPlaceholder: 'Example: 5',
        returnDayOfMonthHelp: 'Return will be added automatically on the same day each month',
        day: 'Day',
        ofEachMonth: 'of each month',
        lastReturnDate: 'Last Return Date',
        savingsFund: 'Savings Fund',
        maxWithdrawalLimit: 'Maximum Withdrawal Limit',
        maxWithdrawalLimitPlaceholder: 'Leave empty if equal to certificate value',
        maxWithdrawalLimitHelp: 'Credit limit allowed by the bank for withdrawal (optional - if less than certificate value)',
        maxWithdrawalLimitExceedsAmount: 'Maximum withdrawal limit cannot exceed certificate amount',
        gold: 'Gold',
        addGoldPurchase: 'Add Gold Purchase',
        goldPurchases: 'Purchases',
        goldPurchasesList: 'Purchases List',
        noGoldPurchases: 'No gold purchases',
        invoiceValue: 'Invoice Value',
        grams: 'Grams',
        gram: 'Gram',
        pricePerGram: 'Price per Gram',
        purity: 'Purity',
        carat: 'Carat',
        goldType: 'Gold Type',
        goldBar: 'Gold Bar',
        goldCoin: 'Gold Coin',
        halfGoldCoin: 'Half Gold Coin',
        quarterGoldCoin: 'Quarter Gold Coin',
        goldRing: 'Ring',
        goldEarring: 'Earring',
        goldNecklace: 'Necklace',
        goldBracelet: 'Bracelet',
        goldChain: 'Chain',
        goldPendant: 'Pendant',
        goldBrooch: 'Brooch',
        otherGold: 'Other',
        purchaseDate: 'Purchase Date',
        remaining: 'Remaining',
        sold: 'Sold',
        sellGold: 'Sell Gold',
        sell: 'Sell',
        saleValue: 'Sale Value',
        saleDate: 'Sale Date',
        salesHistory: 'Sales History',
        profitLoss: 'Profit/Loss',
        purchaseInfo: 'Purchase Info',
        totalGoldPurchases: 'Total Purchases',
        totalGoldSales: 'Total Sales',
        totalProfitLoss: 'Total Profit/Loss',
        insufficientGold: 'Insufficient gold',
        pleaseEnterValidValues: 'Please enter valid values',
        thisMonth: 'This Month',
        lastMonth: 'Last Month',
        thisYear: 'This Year',
        totalIncome: 'Total Income',
        totalExpenses: 'Total Expenses',
        expensesByCategory: 'Expenses by Category',
        monthlyComparison: 'Monthly Comparison',
        optimization: 'Optimization',
        recommendations: 'Recommendations',
        savingsOpportunities: 'Savings Opportunities',
        tooManyRecurring: 'Too Many Recurring Expenses',
        recurringRecommendation: 'Review recurring expenses and cancel unnecessary ones',
        highSpending: 'High Spending',
        highSpendingMessage: 'Your spending on',
        isHigh: 'is high. You can optimize it',
        savingsGoal: 'Savings Goal',
        savingsGoalMessage: 'Try to save 20% of your monthly income',
        noData: 'Not enough data for analysis',
        tips: 'Tips',
        foodTip1: 'Cook meals for the week',
        foodTip2: 'Use a shopping list and stick to it',
        foodTip3: 'Avoid eating out frequently',
        transportTip1: 'Use public transportation',
        transportTip2: 'Share rides with others',
        transportTip3: 'Use a bike for short distances',
        billsTip1: 'Turn off unused devices',
        billsTip2: 'Use energy-saving LED bulbs',
        billsTip3: 'Monitor water and electricity usage',
        shoppingTip1: 'Compare prices before buying',
        shoppingTip2: 'Use discount coupons',
        shoppingTip3: 'Avoid emotional shopping',
        generalTip1: 'Monitor your expenses regularly',
        generalTip2: 'Set a monthly budget',
        generalTip3: 'Save 20% of your income every month',
        currentSpending: 'Current Spending',
        potentialSaving: 'Potential Saving',
        language: 'Language',
        general: 'General',
        soundNotifications: 'Sound Notifications',
        soundNotificationsDesc: 'Enable sounds for notifications',
        emailNotifications: 'Email Notifications',
        emailNotificationsDesc: 'Send notifications via email',
        email: 'Email',
        enterEmail: 'Enter Email',
        exportBackup: 'Export Backup',
        exportBackupDesc: 'Save all your data as a JSON file',
        export: 'Export',
        importBackup: 'Import Backup',
        importBackupDesc: 'Restore data from backup file',
        import: 'Import',
        appearance: 'Appearance',
        theme: 'Theme',
        light: 'Light',
        dark: 'Dark',
        auto: 'Auto',
        backupExported: 'Backup exported successfully',
        backupImported: 'Backup imported successfully',
        backupError: 'An error occurred',
        monthlyRecurring: 'Monthly Recurring Salary',
        dayOfMonth: 'Day of Month',
        dayOfMonthPlaceholder: 'e.g., 5',
        dayOfMonthHelp: 'Salary will be added automatically on the same day each month',
        ofEachMonth: 'of each month',
        recurringSalaries: 'Recurring Monthly Salaries',
        regularSalaries: 'Regular Salaries',
        lastAdded: 'Last Added',
        checkNow: 'Check Now',
        autoAdded: 'Auto Added',
        salaryAdded: 'Salary Added Automatically',
        monthlyExpense: 'Monthly Expense',
        autoAddMonthly: 'Auto Add Monthly',
        expenseDayOfMonthHelp: 'Expense will be added automatically on the same day each month',
        recurringMonthlyExpenses: 'Recurring Monthly Expenses',
        regularExpenses: 'Regular Expenses',
        manageCategories: 'Manage Categories',
        categoryName: 'Category Name',
        enterCategoryName: 'Enter Category Name',
        icon: 'Icon',
        color: 'Color',
        addCategory: 'Add Category',
        existingCategories: 'Existing Categories',
        cannotDeleteDefault: 'Cannot delete default category',
        errorAddingCategory: 'Error adding category',
        errorDeletingCategory: 'Error deleting category',
        expenseAdded: 'Expense Added Automatically',
        totalSalaries: 'Total Salaries',
        pleaseEnterCategoryName: 'Please enter category name',
        categoryAlreadyExists: 'Category already exists',
        databaseError: 'Database error. Please refresh the page',
        categoryAddedSuccessfully: 'Category added successfully',
        noCategories: 'No categories',
        confirmDeleteCategory: 'Are you sure you want to delete this category?',
        categoryDeletedSuccessfully: 'Category deleted successfully',
        deleteAllData: 'Delete All Data',
        deleteAllDataDesc: 'A backup will be created automatically before deletion, then all data will be permanently deleted',
        deleteAll: 'Delete All',
        dangerZone: 'Danger Zone',
        confirmDeleteAllData: '⚠️ Warning: All data will be deleted!\n\nA backup will be created automatically before deletion.\nAre you absolutely sure?\n\nType "delete" to confirm:',
        finalConfirmDelete: '⚠️ Final Confirmation!\n\nAll your data will be permanently deleted.\nBackup has already been created.\n\nAre you 100% sure?',
        allDataDeleted: 'All data deleted successfully. Automatic backup was created.',
        allDataDeletedSuccess: '✅ All data deleted successfully!\n\nAutomatic backup was created before deletion.\nThe page will reload now.',
        deleteError: 'Error occurred while deleting data',
        deleteCancelled: 'Operation cancelled. No data was deleted.',
        backupFailedBeforeDelete: 'Failed to create backup before deletion',
        errorCheckingExpenses: 'Error checking recurring expenses',
        // Activity Log
        activityLog: 'Activity Log',
        filters: 'Filters',
        entityType: 'Entity Type',
        action: 'Action',
        clearFilters: 'Clear Filters',
        clearOldActivities: 'Delete Old Records',
        clearAllActivities: 'Delete All Records',
        confirmClearOldActivities: 'Do you want to delete records older than one year?',
        oldActivitiesCleared: 'Old records deleted successfully',
        confirmClearAllActivities: 'Are you sure you want to delete all records?',
        allActivitiesCleared: 'All records have been deleted',
        noActivities: 'No activities recorded',
        added: 'Added',
        updated: 'Updated',
        deleted: 'Deleted',
        sold: 'Sold',
        purchased: 'Purchased',
        repaid: 'Repaid',
        withdrawn: 'Withdrawn',
        paid: 'Paid',
        // Entity labels
        expense: 'Expense',
        salary: 'Salary',
        certificate: 'Certificate',
        certificateWithdrawal: 'Withdrawal',
        goldPurchase: 'Gold Purchase',
        goldSale: 'Gold Sale',
        goal: 'Goal',
        category: 'Category'
    }
};

let currentLanguage = 'ar';

export const setLanguage = (lang) => {
    currentLanguage = lang;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('msarefy_language', lang);
};

export const getLanguage = () => {
    return currentLanguage || localStorage.getItem('msarefy_language') || 'ar';
};

export const t = (key) => {
    const lang = getLanguage();
    return translations[lang]?.[key] || key;
};

// Initialize language on load
if (typeof window !== 'undefined') {
    const savedLang = localStorage.getItem('msarefy_language') || 'ar';
    setLanguage(savedLang);
}
